### ISSUE TITLE
블록 요소에 margin: 0 auto; 적용이 안됨

### ISSUE THREAD

**Issue by jiseung-kang** [jiseung-kang/ggul-market#2]
이슈 남겨주세요!

**Comment by jiseung-kang** [comment]
이슈 있어요!

**Comment by jiseung-kang** [comment]
> 이슈 있어요!

뭔가요?

**Comment by sooonlog** [comment]
> 이슈 있어요!

지승님이 귀엽다는 이슈입니다!!

**Comment by sooonlog** [comment]
commit 할 때 issue 번호를 잘못 적어서 여기에 질문 사항 남깁니다😅 
블록 요소를 중앙 정렬 할 때, margin: 0 auto가 안 먹는 문제가 발생했습니다.

해결을 위해 부모 요소인 body에도 width: 100%를 줘보고, 
정렬이 필요한 h1 태그에도 width: 100%를 줘봤는데, 적용이 안되더라구요ㅠㅠ

개발자 도구에서 block으로 속성이 되어있다는 것도 확인했는데 무슨 이유로 적용이 안되는지 궁금합니다!
혹시 왜 안되는지에 대해 아시는 분이 있으면 코멘트 부탁드려요 ( •̀ ω •́ )✧

**Comment by jiseung-kang** [comment]
> commit 할 때 issue 번호를 잘못 적어서 여기에 질문 사항 남깁니다😅 블록 요소를 중앙 정렬 할 때, margin: 0 auto가 안 먹는 문제가 발생했습니다.
> 
> 해결을 위해 부모 요소인 body에도 width: 100%를 줘보고, 정렬이 필요한 h1 태그에도 width: 100%를 줘봤는데, 적용이 안되더라구요ㅠㅠ
> 
> 개발자 도구에서 block으로 속성이 되어있다는 것도 확인했는데 무슨 이유로 적용이 안되는지 궁금합니다! 혹시 왜 안되는지에 대해 아시는 분이 있으면 코멘트 부탁드려요 ( •̀ ω •́ )✧

**Comment by jiseung-kang** [comment]
<h1 class="tit-name">로그인</h1>
제가 이해한게 맞다면 '로그인'이라는 텍스트가 중앙정렬이 안되는 부분에서 고민하신 것 같은데!

<h1 class="tit-name"></h1> <- 이 요소는 중앙정렬이 된 것이 맞고,
안에 있는 텍스트(로그인)는 요소 안에 들어있는 내용이기 때문에 
1. text-align: center; 로 텍스트를 중앙정렬하거나, 
2. 2. 지금 해주신 것처럼 padding을 주어서 요소 내부에서 텍스트를 중앙정렬할 수 있을 것 같아요.
